### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by arthurlutz** [philadams/habitica#13]
On my selfhosted habitica installation I get : 

```
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/habitica/bin/habitica", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/arthur/local/habitica/bin/habitica", line 13, in <module>
    habitica.cli()
  File "/home/arthur/local/habitica/habitica/core.py", line 188, in cli
    if party['quest'] and party['quest']['active']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

maybe it's because I'm using an "older" version of the API or that I have no active quest ? I'm running habitica v1.1.0

**Comment by philadams-zz** [comment]
Hmm. HEAD _sometimes_ has some janky stuff in there while I'm trying to figure out the most sane way to do certain things. E.g. https://github.com/HabitRPG/habitrpg/issues/5795 relates to me trying to understand all quest types and how those data are organized in the API.

The issue you're running up against was an oversight fixed by a contributor - the current release 0.0.12 doesn't freak out in this way (https://github.com/philadams/habitica/blob/3534d9cc472d9067961aed76cba6ed1d94524463/habitica/core.py).

Thank you so much for your input!
